### ISSUE TITLE
ValueError: list.remove(x): x not in list

### ISSUE THREAD

**Issue by matkoniecz** [thearn/examgen#2]
It is not always appearing, though it is not just a freak accident.
```
python example_worksheet.py 
Traceback (most recent call last):
  File "example_worksheet.py", line 8, in <module>
    "Solve the following equations for the specified variable.")
  File "/home/mateusz/Desktop/tmp/examgen/examgen/worksheet.py", line 89, in add_section
    p, sols = prob_generator(*args, **kwargs)
  File "/home/mateusz/Desktop/tmp/examgen/examgen/lib/algebra.py", line 77, in make_linear_eq
    exclude = exclude)
  File "/home/mateusz/Desktop/tmp/examgen/examgen/lib/helper.py", line 38, in get_coefficients
    selection.remove(i)
ValueError: list.remove(x): x not in list
```

**Comment by matkoniecz** [comment]
I need tool like this, and this seems to be the most advanced open source math exam generator.

But I am unsure whatever I should send PRs, so far I send two trivial probing ones.

**Comment by wvhulle** [comment]
Yes it seems like a good tool. Did you get anything to work recently?

**Comment by barnabartos** [comment]
@matkoniecz @wvhulle @thearn

Greetings, i stumbled upon this project, and it is something i need as well. I have sent an email to the original author, I did not get an answer yet. All forks seemed to be inactive. Did you guys get anything done?

I would be happy to adopt this project. I forked it and ported it to python3 on my local version, didn't push it yet. I will start working on tests next, i have experience as a test engineer. I am looking for this bug right now.

**Comment by wvhulle** [comment]
Oh you ported it? That's good. I build my own exam generator meanwhile. I
just had to generate prealgebra exams. It constructs expression trees with
integer solutions and also gives solutions with sympy. Output is a pdf
exam.

**Comment by thearn** [comment]
I haven't used this library in quite a few years! I haven't been lecturing. But I'm glad that others have found it useful.
I think that I was able to fix this with the latest push. This also includes an update for Python3 and the latest Sympy.
