### ISSUE TITLE
LaTeX is complaining about single column

### ISSUE THREAD

**Issue by matkoniecz** [thearn/examgen#4]
`python example_exam.py` in LaTeX stage emits multiple warnings, among them is

```
Package multicol Warning: Using `1' columns doesn't seem a good idea.
 I therefore use two columns instead on input line 12.
```

**Comment by thearn** [comment]
I haven't used this library in quite a few years! I haven't been lecturing. But I'm glad that others have found it useful.
I think that I was able to fix this with the latest push. This also includes an update for Python3 and the latest Sympy.
